### ISSUE TITLE
Implement CityGenerator

### ISSUE THREAD

**Issue by m-mathilde34** [m-mathilde34/Traveling-Salesman---Genetic-Algorithm#17]

**Comment by m-mathilde34** [comment]
@trav-d13 I'm currently implementing this branch. Am I right in thinking that I will need to create an ArrayList of City where I put all my created cities, and then write it onto a file? So far I have mapped what I am planning to do by creating skeleton methods, adding comments and adding the class' parameters. Can you tell me if it looks right? Thank you very much in advance,

**Comment by trav-d13** [comment]
Hey @m-mathilde34, your skeleton class and functions look good. 
Your comments regarding `generateListOfCities()` seem fantastic! 
I would suggest adding an additional method that can access your already generated cities in the `public ArrayList<City> generatedCities;` field and allows for a `newCity` parameter to determine if its in an acceptable distance to the already created cities. 
I really like the framework! 
Good luck with the implementation!!

**Comment by m-mathilde34** [comment]
@trav-d13 Thank you so much for having a look through the class! Am I right in thinking that I don't have to write each city to a file then as they will be put in the ArrayList<> ?
Hopefully I can get that done by next week and then it will literally just be putting it all together! How exciting!!

**Comment by m-mathilde34** [comment]
@trav-d13 Hi Travis! I've implemented most of the CityGenerator class now. I'm trying to create my methods to handle File operations now. I would like to save data to a CSV file like we discussed but am struggling using Java with CSV. I believe the OpenCSV library can help with that. Reading up on geeksforgeeks (https://www.geeksforgeeks.org/reading-csv-file-java-using-opencsv/) I see that there is a way to use it with Gradle but am not sure how to go about it. Could you please give me some advice? Thank you so much in advance!
